services:
  web:
    image: ghcr.io/aetherunbound/ollama-dashboard
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_HOST=<host>
      - OLLAMA_PORT=11434
    volumes:
      - ./data/history.json:/app/history.json
